name: build java application
on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: clonar codigo
        uses: actions/checkout@v6
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: instalar java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: compilar y ejecutar test
        run: mvn verify 
      - name: Publicar reporte de jacoco
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-report
          path: target/site/jacoco
  empaquetar:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: clonar codigo
        uses: actions/checkout@v6
      - name: verificar version de java
        run: java -version
      - name: instalar java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: verificar version de java
        run: java -version
      - name: empaquetar aplicacion
        run: mvn package -DskipTests
      - name: Publicar paquete
        uses: actions/upload-artifact@v6
        with:
          name: maven-app
          path: target/*.jar
