name: build java application
on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: clonar codigo
        uses: actions/checkout@v6
      - name: instalar java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: compilar codigo
        run: mvn compile
      - name: ejecutar test
        run: mvn test
  empaquetar:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: clonar codigo
        uses: actions/checkout@v6
      - name: empaquetar aplicacion
        run: mvn package -DskipTests
